name: build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: List directories for debugging
      run: |
        echo "Current directory:"
        pwd
        echo "Listing all files recursively:"
        ls -R

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x 

    - name: Configure locale for Russian language
      run: |
        sudo apt-get update
        sudo apt-get install -y locales
        sudo locale-gen ru_RU.UTF-8
        export LANG=ru_RU.UTF-8
        export LC_ALL=ru_RU.UTF-8
      env:
        DOTNET_CLI_UI_LANGUAGE: ru

    - name: Restore dependencies
      run: |
        dotnet restore Fabric/Fabrics.sln

    - name: Build
      run: |
        dotnet build Fabric/Fabrics.Domain/Fabrics.Domain.csproj --no-restore
        dotnet build Fabric/Fabrics.Test/Fabrics.Test.csproj --no-restore

    - name: Test
      run: dotnet test Fabric/Fabrics.Test/Fabrics.Test.csproj --no-build --verbosity normal
