name: build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: List directories for debugging
      run: |
        echo "Current directory:"
        pwd
        echo "Listing all files recursively:"
        ls -R

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: |
        dotnet restore Factory/Factory/Factory.Model.csproj
        dotnet restore Factory/Factory.Test/Factory.Test.csproj

    - name: Build
      run: |
        dotnet build Factory/Factory/Factory.Model.csproj --no-restore
        dotnet build Factory/Factory.Test/Factory.Test.csproj --no-restore

    - name: Test
      run: dotnet test Factory/Factory.Test/Factory.Test.csproj --no-build --verbosity normal